---
- name: Install flatpak in Ubuntu system
  apt:
    name: ['flatpak', 'gnome-software-plugin-flatpak']
    state: present
  when: ansible_facts['os_family']|lower == 'ubuntu'

- name: Add the Flathub repository
  shell: flatpak remote-add --if-not-exists flathub {{ Flathub_URL }}
